    version: 1.2
    workflows:
        - subclass: WDL
          primaryDescriptorPath: /steamer.wdl  # absolute path
          testParameterFiles: <String Array>  # absolute path
          readMePath: /README.md # absolute path
          authors:
              - name: Andrew Robbins
                email: robbiand@med.umich.edu
                orcid: 0009-0001-7961-7489
              - name: Crystal Wen
                email: mccwen@umich.edu
          topic: The welch-lab STEAMER pipeline
